### PR TITLE
Add new Logo to Surelock

### LINKED ISSUE #6: Logo
we need a logo :)

maybe simply a lock with an "S" on it?

ideas?

### PR DESCRIPTION
**Pull request by tschitschable**
Hello

I made a logo for Surelock. 

Fixes #6

### CODE REVIEW

**Comment by xorond** [comment]
hi,

thanks! could you remove the file `.DS_Store` from your pull request?

**Comment by tschitschable** [comment]
Yes, will do asap.

**Comment by tschitschable** [comment]
@xorond done! :)

**Comment by xorond** [comment]
merged, thanks!

**Pull request merged**
